### ISSUE TITLE
Save and Close visible from CME Home

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TridionCommunity/tridion-powertools#42]
```
What steps will reproduce the problem?
1. Go to the CME Home Tab
2. The Save & Close button is visible
3. The button doesn't seem to enable based on selection

What is the expected output? What do you see instead?

I expect to either:
1. Be able to save and comment on items when browsing
2. Or, preferably, _not_ see the button in the Home tab.



```

Original issue reported on code.google.com by `reyes.al...@gmail.com` on 5 Nov 2012 at 4:43

**Comment by Nivlong** [comment]
I'm not seeing on an SDL Tridion 2013 SP1 PowerTools install. I'll revisit if it comes up again.

I do see Save and Comment in a Publication, but I'm not sure it's intentional. The original documentation mentions Save & Comment should work on Components and Pages, but can be "enabled" for other item types.
